import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class ProfilService {

  // Liste complète des profils organisés par domaine
  private readonly availableProfils: string[] = [
    // Informatique & Technologies
    'Développeur Web Frontend',
    'Développeur Web Backend',
    'Développeur Full Stack',
    'Développeur Mobile iOS',
    'Développeur Mobile Android',
    'Développeur React Native',
    'Développeur Flutter',
    'Data Scientist',
    'Data Analyst',
    'Data Engineer',
    'Ingénieur DevOps',
    'Ingénieur Cloud (AWS/Azure/GCP)',
    'Administrateur Système',
    'Administrateur Réseau',
    'Ingénieur Sécurité / Cybersécurité',
    'Architecte Logiciel',
    'Architecte Cloud',
    'Testeur QA / Quality Assurance',
    'Ingénieur Machine Learning',
    'Ingénieur IA / Intelligence Artificielle',
    'Designer UI/UX',
    'Webdesigner',
    'Product Designer',
    'Graphic Designer',
    'Scrum Master',
    'Product Owner',
    'Chef de Projet IT',
    'Product Manager',
    'Business Analyst',
    'Technicien Informatique',
    'Support Technique',
    'Technicien Helpdesk',

    // BTP & Construction
    'Maçon',
    'Chef de Chantier',
    'Conducteur de Travaux',
    'Ingénieur BTP',
    'Ingénieur Civil',
    'Architecte',
    'Dessinateur en Bâtiment',
    'Métreur',
    'Charpentier',
    'Menuisier',
    'Ébéniste',
    'Carreleur',
    'Peintre en Bâtiment',
    'Plâtrier',
    'Couvreur',
    'Zingueur',
    'Étancheur',
    'Maçon-coffreur',
    'Ferrailleur',
    'Terrassier',
    'Canalisateur',
    'Géomètre',

    // Électricité & Énergie
    'Électricien',
    'Électricien Industriel',
    'Électricien Bâtiment',
    'Électrotechnicien',
    'Technicien en Automatisme',
    'Ingénieur Électrique',
    'Technicien Électronicien',
    'Monteur-Câbleur',
    'Technicien Fibre Optique',
    'Technicien Énergies Renouvelables',
    'Installateur Photovoltaïque',

    // Plomberie & Chauffage
    'Plombier',
    'Plombier-Chauffagiste',
    'Chauffagiste',
    'Installateur Sanitaire',
    'Technicien CVC (Climatisation Ventilation Chauffage)',
    'Frigoriste',
    'Climaticien',
    'Tuyauteur',

    // Mécanique & Automobile
    'Mécanicien Automobile',
    'Technicien Automobile',
    'Carrossier',
    'Peintre Automobile',
    'Mécanicien Poids Lourds',
    'Mécanicien Moto',
    'Mécanicien Agricole',
    'Mécanicien Industriel',
    'Technicien de Maintenance',
    'Agent de Maintenance',
    'Électromécanicien',
    'Tourneur-Fraiseur',
    'Usineur',
    'Soudeur',
    'Chaudronnier',
    'Tuyauteur Industriel',
    'Ajusteur-Monteur',

    // Santé & Médical
    'Médecin Généraliste',
    'Médecin Spécialiste',
    'Chirurgien',
    'Infirmier',
    'Infirmier Anesthésiste',
    'Infirmier de Bloc Opératoire',
    'Aide-Soignant',
    'Auxiliaire de Puériculture',
    'Sage-Femme',
    'Pharmacien',
    'Préparateur en Pharmacie',
    'Kinésithérapeute',
    'Ergothérapeute',
    'Orthophoniste',
    'Psychologue',
    'Psychiatre',
    'Radiologue',
    'Biologiste Médical',
    'Laborantin',
    'Dentiste',
    'Prothésiste Dentaire',
    'Opticien',
    'Audioprothésiste',
    'Ambulancier',
    'Brancardier',
    'Aide Médico-Psychologique',
    'Agent Hospitalier',

    // Administration & Gestion
    'Secrétaire',
    'Assistant Administratif',
    'Secrétaire de Direction',
    'Assistant de Gestion',
    'Gestionnaire Administratif',
    'Office Manager',
    'Responsable Administratif',
    'Comptable',
    'Assistant Comptable',
    'Chef Comptable',
    'Contrôleur de Gestion',
    'Auditeur',
    'Expert-Comptable',
    'Gestionnaire de Paie',
    'Assistant Juridique',
    'Juriste',
    'Avocat',
    'Notaire',

    // Ressources Humaines
    'Responsable RH',
    'Chargé de Recrutement',
    'Responsable Recrutement',
    'Chargé de Formation',
    'Responsable Formation',
    'Gestionnaire RH',
    'Assistant RH',
    'Responsable Paie',

    // Commerce & Vente
    'Vendeur',
    'Conseiller de Vente',
    'Commercial',
    'Technico-Commercial',
    'Commercial Terrain',
    'Commercial Sédentaire',
    'Responsable Commercial',
    'Directeur Commercial',
    'Chef des Ventes',
    'Ingénieur Commercial',
    'Account Manager',
    'Business Developer',
    'Responsable Grand Compte',
    'Chargé d\'Affaires',
    'Acheteur',
    'Responsable Achats',
    'Category Manager',
    'Trade Marketeur',
    'Merchandiser',
    'Responsable de Magasin',
    'Chef de Rayon',
    'Caissier',
    'Hôte de Caisse',

    // Marketing & Communication
    'Responsable Marketing',
    'Chargé de Marketing',
    'Chef de Produit',
    'Digital Marketeur',
    'Traffic Manager',
    'Community Manager',
    'Social Media Manager',
    'Content Manager',
    'Responsable Communication',
    'Chargé de Communication',
    'Chargé de Relations Publiques',
    'Attaché de Presse',
    'Rédacteur Web',
    'SEO Manager',
    'SEM Manager',
    'Growth Hacker',

    // Logistique & Transport
    'Chauffeur Livreur',
    'Chauffeur Poids Lourd',
    'Chauffeur VL',
    'Conducteur de Bus',
    'Conducteur de Train',
    'Cariste',
    'Magasinier',
    'Agent Logistique',
    'Préparateur de Commandes',
    'Réceptionnaire',
    'Responsable Logistique',
    'Responsable d\'Entrepôt',
    'Supply Chain Manager',
    'Responsable Expéditions',
    'Affréteur',
    'Dispatcher',
    'Coursier',

    // Hôtellerie & Restauration
    'Chef Cuisinier',
    'Cuisinier',
    'Commis de Cuisine',
    'Pâtissier',
    'Boulanger',
    'Serveur',
    'Barman / Barmaid',
    'Sommelier',
    'Maître d\'Hôtel',
    'Directeur de Restaurant',
    'Pizzaiolo',
    'Plongeur',
    'Réceptionniste d\'Hôtel',
    'Concierge d\'Hôtel',
    'Gouvernante',
    'Femme de Chambre',
    'Valet',
    'Directeur d\'Hôtel',
    'Revenue Manager',
    'Chef de Rang',

    // Nettoyage & Services
    'Agent d\'Entretien',
    'Agent de Nettoyage',
    'Agent de Propreté',
    'Responsable Propreté',
    'Agent de Service Hospitalier',
    'Agent de Blanchisserie',

    // Sécurité & Surveillance
    'Agent de Sécurité',
    'Vigile',
    'Garde du Corps',
    'Agent de Sûreté Aéroportuaire',
    'Agent Cynophile',
    'Responsable Sécurité',
    'Sapeur-Pompier',

    // Éducation & Formation
    'Professeur des Écoles',
    'Enseignant Collège/Lycée',
    'Professeur de Français',
    'Professeur de Mathématiques',
    'Professeur d\'Anglais',
    'Professeur d\'Histoire-Géographie',
    'Professeur de Sciences',
    'Professeur de Sport / EPS',
    'Professeur d\'Arts Plastiques',
    'Professeur de Musique',
    'Professeur Particulier',
    'Formateur',
    'Formateur Professionnel',
    'Conseiller Pédagogique',
    'Éducateur Spécialisé',
    'Moniteur-Éducateur',
    'Animateur',
    'Directeur d\'École',

    // Agriculture & Environnement
    'Agriculteur',
    'Éleveur',
    'Maraîcher',
    'Viticulteur',
    'Ouvrier Agricole',
    'Chef de Culture',
    'Conducteur d\'Engins Agricoles',
    'Technicien Agricole',
    'Ingénieur Agronome',
    'Paysagiste',
    'Jardinier',
    'Élagueur',
    'Bûcheron',
    'Agent d\'Entretien Espaces Verts',
    'Responsable Environnement',
    'Technicien Environnement',
    'Ingénieur Environnement',

    // Production & Industrie
    'Opérateur de Production',
    'Conducteur de Ligne',
    'Régleur',
    'Technicien de Production',
    'Responsable de Production',
    'Ingénieur de Production',
    'Contrôleur Qualité',
    'Responsable Qualité',
    'Ingénieur Qualité',
    'Technicien Méthodes',
    'Ingénieur Méthodes',
    'Technicien Industrialisation',

    // Artisanat & Métiers d\'Art
    'Bijoutier',
    'Horloger',
    'Couturier / Couturière',
    'Modiste',
    'Cordonnier',
    'Tapissier',
    'Relieur',
    'Céramiste',
    'Souffleur de Verre',
    'Forgeron',
    'Sculpteur',
    'Restaurateur d\'Art',

    // Autres
    'Coiffeur / Coiffeuse',
    'Esthéticien / Esthéticienne',
    'Prothésiste Ongulaire',
    'Barbier',
    'Tatoueur',
    'Masseur / Masseuse',
    'Coach Sportif',
    'Photographe',
    'Vidéaste',
    'Monteur Vidéo',
    'Journaliste',
    'Rédacteur',
    'Traducteur',
    'Interprète',
    'Bibliothécaire',
    'Archiviste',
    'Agent Immobilier',
    'Clerc de Notaire',
    'Huissier de Justice',
    'Courtier en Assurance',
    'Conseiller Clientèle',
    'Conseiller Bancaire',
    'Gestionnaire de Patrimoine',
    'Analyste Financier',
    'Trader',
    'Autre'
  ];

  constructor() { }

  /**
   * Retourne la liste complète des profils disponibles
   */
  getAllProfils(): string[] {
    return [...this.availableProfils];
  }

  /**
   * Filtre les profils selon une recherche
   */
  filterProfils(search: string): string[] {
    if (!search || search.trim() === '') {
      return this.getAllProfils();
    }

    const searchLower = search.toLowerCase().trim();
    return this.availableProfils.filter(profil =>
      profil.toLowerCase().includes(searchLower)
    );
  }
}
